import {
  PaymentItem,
  ServicingItem,
  UserItem,
  EnergyDealerItem,
  RepairmenItem,
} from '@/types'

export const ChargingData: PaymentItem[] = [
  {
    id: 1,
    name: 'Abu-Ekpeshie Emmanuel',
    status: 'active',
    phoneNumber: '+2348123456789',
    email: 'emmanuelabu@mail.com',
    rating: 4,
    lastlogin: '28/05/21',
  },
  {
    id: 2,
    name: 'Abu-Ekpeshie Emmanuel',
    status: 'inactive',
    phoneNumber: '+2348123456789',
    email: 'emmanuelabu@mail.com',
    rating: 4,
    lastlogin: '28/05/21',
  },
  {
    id: 3,
    name: 'Abu-Ekpeshie Emmanuel',
    status: 'active',
    phoneNumber: '+2348123456789',
    email: 'emmanuelabu@mail.com',
    rating: 4,
    lastlogin: '28/05/21',
  },
  {
    id: 4,
    name: 'Abu-Ekpeshie Emmanuel',
    status: 'inactive',
    phoneNumber: '+2348123456789',
    email: 'emmanuelabu@mail.com',
    rating: 4,
    lastlogin: '28/05/21',
  },
  {
    id: 5,
    name: 'Abu-Ekpeshie Emmanuel',
    status: 'active',
    phoneNumber: '+2348123456789',
    email: 'emmanuelabu@mail.com',
    rating: 4,
    lastlogin: '28/05/21',
  },
  {
    id: 6,
    name: 'Abu-Ekpeshie Emmanuel',
    status: 'inactive',
    phoneNumber: '+2348123456789',
    email: 'emmanuelabu@mail.com',
    rating: 4,
    lastlogin: '28/05/21',
  },
  {
    id: 7,
    name: 'Abu-Ekpeshie Emmanuel',
    status: 'active',
    phoneNumber: '+2348123456789',
    email: 'emmanuelabu@mail.com',
    rating: 4,
    lastlogin: '28/05/21',
  },
  {
    id: 8,
    name: 'Abu-Ekpeshie Emmanuel',
    status: 'active',
    phoneNumber: '+2348123456789',
    email: 'emmanuelabu@mail.com',
    rating: 4,
    lastlogin: '28/05/21',
  },
  {
    id: 9,
    name: 'Abu-Ekpeshie Emmanuel',
    status: 'active',
    phoneNumber: '+2348123456789',
    email: 'emmanuelabu@mail.com',
    rating: 4,
    lastlogin: '28/05/21',
  },
]

export const ServicingData: ServicingItem[] = [
  {
    id: 1,
    name: 'Abu-Ekpeshie Emmanuel',
    status: 'accepted',
    phoneNumber: '+2348123456789',
    vehicleName: 'Honda Clarity Electric',
    rating: 4,
    servicingStatus: 'complete',
  },
  {
    id: 2,
    name: 'Abu-Ekpeshie Emmanuel',
    status: 'declined',
    phoneNumber: '+2348123456789',
    vehicleName: 'Honda Clarity Electric',
    rating: 4,
    servicingStatus: 'N/A',
  },
  {
    id: 3,
    name: 'Abu-Ekpeshie Emmanuel',
    status: 'pending',
    phoneNumber: '+2348123456789',
    vehicleName: 'Honda Clarity Electric',
    rating: 4,
    servicingStatus: 'N/A',
  },
  {
    id: 4,
    name: 'Abu-Ekpeshie Emmanuel',
    status: 'accepted',
    phoneNumber: '+2348123456789',
    vehicleName: 'Honda Clarity Electric',
    rating: 4,
    servicingStatus: 'ongoing',
  },
  {
    id: 5,
    name: 'Abu-Ekpeshie Emmanuel',
    status: 'accepted',
    phoneNumber: '+2348123456789',
    vehicleName: 'Honda Clarity Electric',
    rating: 4,
    servicingStatus: 'complete',
  },
  {
    id: 6,
    name: 'Abu-Ekpeshie Emmanuel',
    status: 'accepted',
    phoneNumber: '+2348123456789',
    vehicleName: 'Honda Clarity Electric',
    rating: 4,
    servicingStatus: 'ongoing',
  },
  {
    id: 7,
    name: 'Abu-Ekpeshie Emmanuel',
    status: 'pending',
    phoneNumber: '+2348123456789',
    vehicleName: 'Honda Clarity Electric',
    rating: 4,
    servicingStatus: 'N/A',
  },
  {
    id: 8,
    name: 'Abu-Ekpeshie Emmanuel',
    status: 'accepted',
    phoneNumber: '+2348123456789',
    vehicleName: 'Honda Clarity Electric',
    rating: 4,
    servicingStatus: 'complete',
  },
  {
    id: 9,
    name: 'Abu-Ekpeshie Emmanuel',
    status: 'accepted',
    phoneNumber: '+2348123456789',
    vehicleName: 'Honda Clarity Electric',
    rating: 4,
    servicingStatus: 'complete',
  },
]

export const UserTableData: UserItem[] = [
  {
    id: 1,
    name: 'Abu-Ekpeshie Emmanuel',
    userID: '@ekpeshie',
    status: 'active',
    phoneNumber: '+2348123456789',
    email: 'emmanuelabu@mail.com',
    rating: 4,
  },
  {
    id: 2,
    name: 'Abu-Ekpeshie Emmanuel',
    userID: '@ekpeshie',
    status: 'inactive',
    phoneNumber: '+2348123456789',
    email: 'emmanuelabu@mail.com',
    rating: 4,
  },
  {
    id: 3,
    name: 'Abu-Ekpeshie Emmanuel',
    userID: '@ekpeshie',
    status: 'active',
    phoneNumber: '+2348123456789',
    email: 'emmanuelabu@mail.com',
    rating: 4,
  },
  {
    id: 4,
    name: 'Abu-Ekpeshie Emmanuel',
    userID: '@ekpeshie',
    status: 'active',
    phoneNumber: '+2348123456789',
    email: 'emmanuelabu@mail.com',
    rating: 4,
  },
  {
    id: 5,
    name: 'Abu-Ekpeshie Emmanuel',
    userID: '@ekpeshie',
    status: 'active',
    phoneNumber: '+2348123456789',
    email: 'emmanuelabu@mail.com',
    rating: 4,
  },
  {
    id: 6,
    name: 'Abu-Ekpeshie Emmanuel',
    userID: '@ekpeshie',
    status: 'active',
    phoneNumber: '+2348123456789',
    email: 'emmanuelabu@mail.com',
    rating: 4,
  },
  {
    id: 7,
    name: 'Abu-Ekpeshie Emmanuel',
    userID: '@ekpeshie',
    status: 'active',
    phoneNumber: '+2348123456789',
    email: 'emmanuelabu@mail.com',
    rating: 4,
  },
  {
    id: 8,
    name: 'Abu-Ekpeshie Emmanuel',
    userID: '@ekpeshie',
    status: 'active',
    phoneNumber: '+2348123456789',
    email: 'emmanuelabu@mail.com',
    rating: 4,
  },
  {
    id: 9,
    name: 'Abu-Ekpeshie Emmanuel',
    userID: '@ekpeshie',
    status: 'active',
    phoneNumber: '+2348123456789',
    email: 'emmanuelabu@mail.com',
    rating: 4,
  },
]

export const EnergyDealerTableData: EnergyDealerItem[] = [
  {
    id: 1,
    name: 'Abu-Ekpeshie Emmanuel',
    status: 'active',
    phoneNumber: '+2348123456789',
    email: 'emmanuelabu@mail.com',
    rating: 4,
    lastlogin: '28/05/21',
  },
  {
    id: 2,
    name: 'Abu-Ekpeshie Emmanuel',
    status: 'active',
    phoneNumber: '+2348123456789',
    email: 'emmanuelabu@mail.com',
    rating: 4,
    lastlogin: '28/05/21',
  },
  {
    id: 3,
    name: 'Abu-Ekpeshie Emmanuel',
    status: 'active',
    phoneNumber: '+2348123456789',
    email: 'emmanuelabu@mail.com',
    rating: 4,
    lastlogin: '28/05/21',
  },
  {
    id: 4,
    name: 'Abu-Ekpeshie Emmanuel',
    status: 'active',
    phoneNumber: '+2348123456789',
    email: 'emmanuelabu@mail.com',
    rating: 4,
    lastlogin: '28/05/21',
  },
  {
    id: 5,
    name: 'Abu-Ekpeshie Emmanuel',
    status: 'active',
    phoneNumber: '+2348123456789',
    email: 'emmanuelabu@mail.com',
    rating: 4,
    lastlogin: '28/05/21',
  },
  {
    id: 6,
    name: 'Abu-Ekpeshie Emmanuel',
    status: 'active',
    phoneNumber: '+2348123456789',
    email: 'emmanuelabu@mail.com',
    rating: 4,
    lastlogin: '28/05/21',
  },
  {
    id: 7,
    name: 'Abu-Ekpeshie Emmanuel',
    status: 'active',
    phoneNumber: '+2348123456789',
    email: 'emmanuelabu@mail.com',
    rating: 4,
    lastlogin: '28/05/21',
  },
  {
    id: 8,
    name: 'Abu-Ekpeshie Emmanuel',
    status: 'active',
    phoneNumber: '+2348123456789',
    email: 'emmanuelabu@mail.com',
    rating: 4,
    lastlogin: '28/05/21',
  },
  {
    id: 9,
    name: 'Abu-Ekpeshie Emmanuel',
    status: 'active',
    phoneNumber: '+2348123456789',
    email: 'emmanuelabu@mail.com',
    rating: 4,
    lastlogin: '28/05/21',
  },
]

export const RepairmenTableData: RepairmenItem[] = [
  {
    id: 1,
    name: 'Abu-Ekpeshie Emmanuel',
    status: 'active',
    phoneNumber: '+2348123456789',
    email: 'emmanuelabu@mail.com',
    rating: 4,
    lastlogin: '28/05/21',
  },
  {
    id: 2,
    name: 'Abu-Ekpeshie Emmanuel',
    status: 'inactive',
    phoneNumber: '+2348123456789',
    email: 'emmanuelabu@mail.com',
    rating: 4,
    lastlogin: '28/05/21',
  },
  {
    id: 3,
    name: 'Abu-Ekpeshie Emmanuel',
    status: 'active',
    phoneNumber: '+2348123456789',
    email: 'emmanuelabu@mail.com',
    rating: 4,
    lastlogin: '28/05/21',
  },
  {
    id: 4,
    name: 'Abu-Ekpeshie Emmanuel',
    status: 'inactive',
    phoneNumber: '+2348123456789',
    email: 'emmanuelabu@mail.com',
    rating: 4,
    lastlogin: '28/05/21',
  },
  {
    id: 5,
    name: 'Abu-Ekpeshie Emmanuel',
    status: 'active',
    phoneNumber: '+2348123456789',
    email: 'emmanuelabu@mail.com',
    rating: 4,
    lastlogin: '28/05/21',
  },
  {
    id: 6,
    name: 'Abu-Ekpeshie Emmanuel',
    status: 'inactive',
    phoneNumber: '+2348123456789',
    email: 'emmanuelabu@mail.com',
    rating: 4,
    lastlogin: '28/05/21',
  },
  {
    id: 7,
    name: 'Abu-Ekpeshie Emmanuel',
    status: 'active',
    phoneNumber: '+2348123456789',
    email: 'emmanuelabu@mail.com',
    rating: 4,
    lastlogin: '28/05/21',
  },
  {
    id: 8,
    name: 'Abu-Ekpeshie Emmanuel',
    status: 'active',
    phoneNumber: '+2348123456789',
    email: 'emmanuelabu@mail.com',
    rating: 4,
    lastlogin: '28/05/21',
  },
  {
    id: 9,
    name: 'Abu-Ekpeshie Emmanuel',
    status: 'active',
    phoneNumber: '+2348123456789',
    email: 'emmanuelabu@mail.com',
    rating: 4,
    lastlogin: '28/05/21',
  },
]
